### ISSUE TITLE
Problem to start cameabot

### ISSUE THREAD

**Issue by SA7BNT** [tropicoo/camerabot#1]
Hey, 

im trying to use your camerabot but im running in at this issue.

> ads-b@debian:~/camerabot$ python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 164, in <module>
    bot = CameraBotLauncher(conf_path=args.conf_path)
  File "bot.py", line 25, in __init__
    conf = self._load_config(conf_path)
  File "bot.py", line 104, in _load_config
    if not os.path.isfile(path):
  File "/usr/lib/python3.4/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: can't specify None for path argument

I´m using the Hikvision DS-2CD2120F-I 
Can you help me with that?

Greeting 
Tim

**Comment by tropicoo** [comment]
Hey,
Sorry, forgot to update the README and bot itself with printing `help` when no arguments passed.
Could you please try to run it with `python3 bot.py -c config.json` argument, where `config.json` is a relative or absolute path to the config file?
- Taras

**Comment by SA7BNT** [comment]
Now it is working. Great Bot!! 
But still getting some Text. 
Is that a problem?

> Traceback (most recent call last):
  File "bot.py", line 165, in <module>
    bot.run()
  File "bot.py", line 65, in run
    self._directory_watcher.watch()
  File "/home/ads-b/camerabot/camerabot/directorywatcher.py", line 30, in watch
    self._observer.start()
  File "/usr/local/lib/python3.4/dist-packages/watchdog/observers/api.py", line 255, in start
    emitter.start()
  File "/usr/local/lib/python3.4/dist-packages/watchdog/utils/__init__.py", line 110, in start
    self.on_thread_start()
  File "/usr/local/lib/python3.4/dist-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/local/lib/python3.4/dist-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/local/lib/python3.4/dist-packages/watchdog/observers/inotify_c.py", line 199, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/usr/local/lib/python3.4/dist-packages/watchdog/observers/inotify_c.py", line 379, in _add_dir_watch
    raise OSError('Path is not a directory')
OSError: Path is not a directory

**Comment by tropicoo** [comment]
Nice to hear it's working for you. Thanks!
This traceback is caused because `watchdog` from config is being initialized with path placed in `directory` key even if `enabled` is set to `false`. This path probably doesn't exist on your machine so `OSError` is raised.
It isn't a big issue since it doesn't break any functionality and I hope I will update the code during this week to handle this.

**Comment by SA7BNT** [comment]
BTW: Is it possible to have the alarm funktion (line detection, sabotage detection.....) add to the Bot?
